### ISSUE TITLE
Fatal Error: Uncaught TypeError: JkPublishPages::convertDateToTimeStamp():

### ISSUE THREAD

**Issue by ShadowMoses36** [juergenweb/JkPublishPages#2]
Hello, I'm getting an error when trying to save a page. Any ideas what could be the issue? I've not touched any of the modules core.

Thanks in advance

`Fatal Error: Uncaught TypeError: JkPublishPages::convertDateToTimeStamp(): Return value must be of type ?int, string returned in /site/modules/JkPublishPages/JkPublishPages.module:656 Stack trace:
1. /site/modules/JkPublishPages/JkPublishPages.module(676): JkPublishPages->convertDateToTimeStamp('jk_publish_from')
2. /wire/core/Wire.php(416): JkPublishPages->validateDates(Object(HookEvent))
3. /wire/core/WireHooks.php(1097): Wire->_callMethod('validateDates', Array)
4. /wire/core/Wire.php(484): WireHooks->runHooks(Object(InputfieldDatetime), 'processInput', Array)
5. /wire/core/InputfieldWrapper.php(1183): Wire->__call('processInput', Array)
6. /wire/core/Wire.php(416): InputfieldWrapper->___processInput(Object(WireInputData))
7. /wire/core/WireHooks.php(968): Wire->_callMethod('___processInput', Array)
8. /wire/core/Wire.php(484): WireHooks->runHooks(Object(InputfieldFieldsetOpen), 'processInput', Array)
9. /wire/core/InputfieldWrapper.php(1183): Wire->__call('processInput', Array)
10. /wire/core/Wire.php(416): InputfieldWrapper->___processInput(Object(WireInputData))
11. /wire/core/WireHooks.php(968): Wire->_callMethod('___processInput', Array)
12. /wire/core/Wire.php(484): WireHooks->runHooks(Object(InputfieldWrapper), 'processInput', Array)
13. /wire/core/InputfieldWrapper.php(1183): Wire->__call('processInput', Array)
14. /wire/modules/Inputfield/InputfieldForm.module(241): InputfieldWrapper->___processInput(Object(WireInputData))
15. /wire/core/Wire.php(416): InputfieldForm->___processInput(Object(WireInputData))
16. /wire/core/WireHooks.php(968): Wire->_callMethod('___processInput', Array)
17. /wire/core/Wire.php(484): WireHooks->runHooks(Object(InputfieldForm), 'processInput', Array)
18. /wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module(2299): Wire->__call('processInput', Array)
19. /wire/core/Wire.php(416): ProcessPageEdit->___processInput(Object(InputfieldForm))
20. /wire/core/WireHooks.php(968): Wire->_callMethod('___processInput', Array)
21. /wire/core/Wire.php(484): WireHooks->runHooks(Object(ProcessPageEdit), 'processInput', Array)
22. /wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module(2104): Wire->__call('processInput', Array)
23. /wire/modules/Process/ProcessPageEdit/ProcessPageEdit.module(564): ProcessPageEdit->processSave()
24. /wire/core/Wire.php(413): ProcessPageEdit->___execute()
25. /wire/core/WireHooks.php(968): Wire->_callMethod('___execute', Array)
26. /wire/core/Wire.php(484): WireHooks->runHooks(Object(ProcessPageEdit), 'execute', Array)
27. /wire/core/ProcessController.php(361): Wire->__call('execute', Array)
28. /wire/core/Wire.php(413): ProcessController->___execute()
29. /wire/core/WireHooks.php(968): Wire->_callMethod('___execute', Array)
30. /wire/core/Wire.php(484): WireHooks->runHooks(Object(ProcessController), 'execute', Array)
31. /wire/core/admin.php(160): Wire->__call('execute', Array)
32. /wire/modules/AdminTheme/AdminThemeUikit/controller.php(15): require('/home/sites/20b...')
33. /site/templates/admin.php(15): require('/home/sites/20b...')
34. /wire/core/TemplateFile.php(328): require('/home/sites/20b...')
35. /wire/core/Wire.php(413): TemplateFile->___render()
36. /wire/core/WireHooks.php(968): Wire->_callMethod('___render', Array)
37. /wire/core/Wire.php(484): WireHooks->runHooks(Object(TemplateFile), 'render', Array)
38. /wire/modules/PageRender.module(574): Wire->__call('render', Array)
39. /wire/core/Wire.php(416): PageRender->___renderPage(Object(HookEvent))
40. /wire/core/WireHooks.php(968): Wire->_callMethod('___renderPage', Array)
41. /wire/core/Wire.php(484): WireHooks->runHooks(Object(PageRender), 'renderPage', Array)
42. /wire/core/WireHooks.php(1094): Wire->__call('renderPage', Array)
43. /wire/core/Wire.php(484): WireHooks->runHooks(Object(Page), 'render', Array)
44. /wire/modules/Process/ProcessPageView.module(184): Wire->__call('render', Array)
45. /wire/modules/Process/ProcessPageView.module(114): ProcessPageView->renderPage(Object(Page), Object(PagesRequest))
46. /wire/core/Wire.php(416): ProcessPageView->___execute(true)
47. /wire/core/WireHooks.php(968): Wire->_callMethod('___execute', Array)
48. /wire/core/Wire.php(484): WireHooks->runHooks(Object(ProcessPageView), 'execute', Array)
49. /home/sites/20b/6/6bfbd2c2ac/dev/public_html/index.php(55): Wire->__call('execute', Array) #49 {main} thrown
Line 656 of /site/modules/JkPublishPages/JkPublishPages.module`

**Comment by pixelsenseuk** [comment]
When I leave the Publish Until Date empty, it works fine...so the error only appears when setting both dates.

**Comment by juergenweb** [comment]
Hello @ShadowMoses36 

Thanks for reporting this issue. I have found the problem: The date fields for the start and end date will be created automatically. This leads to that the configuration for these 2 fields will not be completely stored inside the database. That is the reason why the property input_type is not stored inside the database, which leads to the given error. I have set this property to 'html' by default to prevent this behaviour. 
Please could you replace the file "JKPublishPages.module" with this one from GitHub and let me know if it works for you now. If everything works as expected, I will bump up the module version afterwards.

Best regards Jürgen

**Comment by pixelsenseuk** [comment]
Hello @juergenweb 

Thank you for this, that makes sense and I can confirm that the above works!

I appreciate your swift fix,

Wayne

**Comment by juergenweb** [comment]
Hi @ShadowMoses36 

Thanks for your feedback, I have updated the module version now.
